import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '../styles/Home.module.css';
import Container from 'react-bootstrap/Container';
import UsersTableClientSide from '../component/table/UsersTableClientSide';
import Footer from '../component/footer/footer';

export default function Example() {
  return (
    <>
      <Head>
        <title>Personal Project - Ajaib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="tablecontainer">
        <UsersTableClientSide />
      </Container>
      <Footer></Footer>
    </>
  );
}
