import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Personal Project - Ajaib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome</h1>
        <button
          type="button"
          className="btn btn-primary"
          onClick={() => router.push('/example')}
        >
          Go To Example
        </button>
        <p>*Client Side Example</p>
        <button
          type="button"
          className="btn btn-primary"
          onClick={() => router.push('/serverside')}
        >
          Go To Example
        </button>
        <p>*Server Side Pagination Example</p>
      </main>

      <footer className={styles.footer}>Sr. Frontend Ajaib Test</footer>
    </div>
  );
}
